<?php include __DIR__ . '/../header.html' ?>
    <div class="container">
        <div class="row">
            <h3>Editar post</h3>
            <form name="form" method="post" action="<?php echo "/posts/{$post->getId()}/update"; ?>">
                <div class="form-group">
                    <label for="title">Título</label>
                    <input type="text" class="form-control" id="title"
                           name="title" placeholder="Digite o título" value="<?php echo $post->getTitle();?>">
                </div>
                <div class="form-group">
                    <label for="content">Conteúdo</label>
                    <textarea class="form-control" id="content" name="content" placeholder="Digite o conteúdo"><?php echo $post->getContent();?></textarea>
                </div>
                <button type="submit" class="btn btn-default">Enviar</button>
            </form>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html' ?>